spring:
  application:
    name: finance-tracker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:15432/finance_tracker}
    username: ${SPRING_DATASOURCE_USERNAME:finance_user}
    password: ${SPRING_DATASOURCE_PASSWORD:finance_pass}

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true